const designSystem = {
  colors: {
    purple: '#7c5dfa',
    lightPurple: '#9277FF',
    darkPurple: '#252945',
    darkerPurple: '#1E2139',
    fadedBlue: '#7E88C3',
    fadedLightBlue: '#DFE3FA',
    fadedDarkBlue: '#888EB0',
    darkerBlue: '#0C0E16',
    danger: '#EC5757',
    fadedRed: '#FF9797',
    WhiteBg: '#F8F8FB',
    darkBlue: '#141625',
    grayBlue: '#373B53',
    white: '#ffffff',
    fadedGrayBlue: '#858BB2',
    green: '#33D69F',
    orange: '#FF8F00',
  },
  fonts: {
    h1: {
      fontFamily: 'Spartan, sans-serif',
      fontWeight: '600',
      fontSize: '32px',
      lineHeight: '36px',
      letterSpacing: '-1px',
    },
    h2: {
      fontFamily: 'Spartan, sans-serif',
      fontWeight: '600',
      fontSize: '20px',
      lineHeight: '22px',
      letterSpacing: '-0.63px',
    },
    h2_2: {
      fontFamily: 'Spartan, sans-serif',
      fontWeight: '600',
      fontSize: '24px',
      lineHeight: '32px',
      letterSpacing: '-0.5px',
    },
    h3_1: {
      fontFamily: 'Spartan, sans-serif',
      fontWeight: '600',
      fontSize: '16px',
      lineHeight: '24px',
      letterSpacing: '-0.8px',
    },
    h3_2: {
      fontFamily: 'Spartan, sans-serif',
      fontWeight: '600',
      fontSize: '12px',
      lineHeight: '15px',
      letterSpacing: '-0.25px',
    },
    p1: {
      fontFamily: 'Spartan, sans-serif',
      fontWeight: '500',
      fontSize: '12px',
      lineHeight: '15px',
      letterSpacing: '-0.25px',
    },
    p2: {
      fontFamily: 'Spartan, sans-serif',
      fontWeight: '500',
      fontSize: '11px',
      lineHeight: '18px',
      letterSpacing: '-0.23px',
    },
  },
  transition:
    'background-color 0.3s ease, color 0.3s ease, fill 0.3s ease, transform 0.3s ease, border 0.3s ease, opacity 0.3s ease',
  boxShadow: {
    light: '0 10px 20px rgba(72, 84, 159, 0.25)',
    dark: '0 10px 20px rgba(0, 0, 0, 0.25)',
  },
}

export default designSystem
