export const designSystem = {
  colors: {
    purple: '#7c5dfa',
    lightPurple: '#9277FF',
    darkPurple: '#252945',
    darkerPurple: '#1E2139',
    fadedBlue: '#7E88C3',
    fadedLightBlue: '#DFE3FA',
    fadedDarkBlue: '#888EB0',
    darkerBlue: '#0C0E16',
    red: '#EC5757',
    fadedRed: '#FF9797',
    WhiteBg: '#F8F8FB',
    darkBlue: '#141625',
  },
  fonts: {
    h1: {
      fontFamily: 'Spartan, sans-serif',
      fontWeight: '600',
      fontSize: 32,
      lineHeight: 36,
      letterSpacing: -1,
    },
    h2: {
      fontFamily: 'Spartan, sans-serif',
      fontWeight: '600',
      fontSize: 20,
      lineHeight: 22,
      letterSpacing: -0.63,
    },
    h3_1: {
      fontFamily: 'Spartan, sans-serif',
      fontWeight: '600',
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: -0.8,
    },
    h3_2: {
      fontFamily: 'Spartan, sans-serif',
      fontWeight: '600',
      fontSize: 12,
      lineHeight: 15,
      letterSpacing: -0.25,
    },
    body_1: {
      fontFamily: 'Spartan, sans-serif',
      fontWeight: '500',
      fontSize: 12,
      lineHeight: 15,
      letterSpacing: -0.25,
    },
    body_2: {
      fontFamily: 'Spartan, sans-serif',
      fontWeight: '500',
      fontSize: 11,
      lineHeight: 18,
      letterSpacing: -0.23,
    },
  },
}
